name: Upload Release

on:
  push:
    tags:
    - 'v*'

env:
  ARCH: NONE

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']

    name: Release
    steps:
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - uses: actions/checkout@v2

      - name: get dependencies
        run: go get -d ./...
        
      - name: build
        run: | 
          go build -o xkcd-image-bot cmd/main.go

      - name: set arch to darwin
        if: startsWith(matrix.os, 'macos')
        run: |
          echo "ARCH=darwin-amd64" >> $GITHUB_ENV

      - name: set arch to linux
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          echo "ARCH=linux-amd64" >> $GITHUB_ENV

      - name: create tarball
        run: |
          tar -czf xkcd-image-bot_${{ env.ARCH }}.tar.gz xkcd-image-bot

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: xkcd-image-bot*tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
